name: latex-builder

on: push
    

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GIT_PAT }}
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex
        
      - name: Release Latest
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.pdf
          tag_name: latest
          name: Latest Version
          draft: true
    
      - name: Release Tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.pdf